# Generated by Django 5.2.1 on 2025-06-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.TextField()),
                ('CreateDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'Images',
            },
        ),
    ]
